name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Using the latest version of the checkout action

    - name: Set up Python
      uses: actions/setup-python@v4  # Using the latest version of the setup-python action
      with:
        python-version: '3.12'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pytest

    - name: Run Black
      run: |
        black --check open_fdd/

    - name: Run tests
      run: |
        pytest open_fdd/tests/
