name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Update to v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black pytest

    - name: Run Black
      run: |
        black --check open_fdd/ tests/

    - name: Run tests
      run: |
        pytest tests/
